### ISSUE TITLE
Any plans to make this library dart 2 compatible?

### ISSUE THREAD

**Issue by martflu** [jimsimon/pub_client#1]
It is depending on `dartson` which is depending on `barback` which is deprecated in dart 2.
You could use [codable](https://pub.dartlang.org/packages/codable) to replace `dartson`. If you don't have the time, I would be willing to create a PR. I just want to make sure first that you are still maintaining this library.

**Comment by jimsimon** [comment]
I haven't touched this library in awhile since I don't use Dart all that
much anymore.  I'm willing to update it if you find it useful though I'm
not even sure if the client methods still point to legitimate pub API
endpoints.

I'd probably switch to json_serializable to eliminate the dependency on
mirrors.  I can do some work on this in the next week or so.

**Comment by martflu** [comment]
We are not super dependent on it but it is the only library with that functionality. json_serializable looks usefull thanks!

**Comment by jimsimon** [comment]
@martflu I've pushed up a new version that requires Dart 2.  You'll need to update to pub_client 2.0.0 to use it.  Let me know if you run into any issues. :)

**Comment by enyo** [comment]
Thanks @jimsimon !
